export const pointers = {
    widget: document.querySelector('#widget'),
    mainPage: document.querySelector('#main'),
    detailsPage: document.querySelector('#details'),
    mainEmptyState: document.querySelector('#main-empty-state'),
    content: document.querySelector('#content'),
    carouselLoadingState: document.querySelector('#carousel-loading-state'),
    itemsListViewLoadingState: document.querySelector('#items-list-view-loading-state'),
    carousel: document.querySelector('#carousel'),
    description: document.querySelector('#description'),
    itemsListView: document.querySelector('#items-list-view'),
    searchInput: document.querySelector('#search-input'),
    iconSearch: document.querySelector('#icon-search'),
    iconSort: document.querySelector('#icon-sort'),
    iconClear: document.querySelector('#icon-clear'),
    itemDetailsEmptyState: document.querySelector('#item-details-empty-state'),
    itemImagesContainer: document.querySelector('#item-images-container'),
    itemImage: document.querySelector('#item-image'),
    itemCoverImage: document.querySelector('#item-cover-image'),
    itemTitle: document.querySelector('#item-title'),
    itemSubtitle: document.querySelector('#item-subtitle'),
    itemDescription: document.querySelector('#item-description'),
    itemImageEmptyState: document.querySelector('#item-image-empty-state'),
    itemCoverImageEmptyState: document.querySelector('#item-cover-image-empty-state'),
}